[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_pgsql", "php82Extensions.pgsql", "php82Extensions.opcache", "curl"]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php",
    "php composer.phar install --no-dev --optimize-autoloader --working-dir=google-api-php-client"
]

[start]
cmd = "php -d opcache.enable=1 -d opcache.memory_consumption=128 -d opcache.max_accelerated_files=10000 -S 0.0.0.0:$PORT -t ."
