[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_pgsql", "php82Extensions.pgsql"]

[phases.install]
cmds = ["echo 'No additional install steps needed'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
